# Generated by Django 4.2 on 2026-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('short_url', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
