# Generated by Django 4.2 on 2026-02-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('profile_photo', models.FileField(upload_to='')),
            ],
        ),
    ]
